CREATE TABLE IF NOT EXISTS Language_Translate(
id INTEGER PRIMARY KEY,
langue VARCHAR(100)  NOT NULL,
message VARCHAR(100)  NOT NULL,
number INTEGER(100) NOT NULL
);

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (1, 1, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (2, 1, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (3, 1, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (4, 2, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (5, 2, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (6, 2, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (7, 3, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (8, 3, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (9, 3, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (10, 4, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (11, 4, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (12, 4, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (13, 5, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (14, 5, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (15, 5, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (16, 6, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (17, 6, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (18, 6, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (19, 7, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (20, 7, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (21, 7, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (22, 8, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (23, 8, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (24, 8, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (25, 9, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (26, 9, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (27, 9, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (28, 10, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (29, 10, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (30, 10, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (31, 11, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (32, 11, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (33, 11, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (34, 12, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (35, 12, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (36, 12, 'EINS', 'DR');

INSERT INTO Language_Translate (ID,NUMBER,MESSAGE,LANGUE) VALUES (37, 13, 'UN', 'FR');
INSERT INTO Language_Translate (ID, NUMBER,MESSAGE,LANGUE) VALUES (38, 13, 'ON', 'EN');
INSERT INTO Language_Translate (ID,NUMBER,MESSAGE, LANGUE) VALUES (39, 13, 'EINS', 'DR');


