
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (1,'Un',1,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (2,'On',1,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (3,'Eins',1,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (4,'Deux',2,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (5,'Two',2,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (6,'Zwei',2,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (7,'Trois',3,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (8,'Tree',3,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (9,'Drei',3,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (10,'Quatre',4,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (11,'Four',4,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (12,'Vier',4,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (13,'Cinq',5,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (14,'Five',5,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (15,'Fünf',5,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (16,'Six',6,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (17,'Six',6,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (18,'Sechs',6,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (19,'Sept',7,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (20,'Seven',7,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (21,'Sieben',7,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (22,'Huit',8,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (23,'Eight',8,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (24,'Acht',8,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (25,'Neuf',9,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (26,'Nine',9,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (27,'Neun',9,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (28,'Dix',10,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (29,'Ten',10,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (30,'Zehn',10,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (31,'Onze',11,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (32,'Eleven',11,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (33,'Elf',11,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (34,'Douze',12,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (35,'Twelve',12,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (36,'Zwölf',12,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (37,'Treize',13,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (38,'Thirteen',13,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (39,'Dreizehn',13,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (40,'Quatorze',14,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (41,'Fourteen',14,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (42,'Vierzehn',14,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (43,'Quinze',15,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (44,'Fifteen',15,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (45,'Fünfzehn',15,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (46,'Seize',16,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (47,'Sixteen',16,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (48,'Sechzehn',16,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (49,'Dix-Sept',17,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (50,'Seventeen',17,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (51,'Siebzehn',17,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (52,'Dix-Huit',18,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (53,'Eighteen',18,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (54,'Achtzehn',18,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (55,'Dix-Neuf',19,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (56,'Nineteen',19,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (57,'Neunzehn',19,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (58,'Vingt',20,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (59,'Twenty',20,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (60,'Zwanzig',20,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (61,'Vingt-Et-Un',21,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (62,'Twenty-One',21,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (63,'Einundzwanzig',21,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (64,'Vingt-Deux',22,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (65,'Twenty-Two',22,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (66,'Zweiundzwanzig',22,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (67,'Vingt-Trois',23,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (68,'Twenty-Three',23,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (69,'Dreiundzwanzig',23,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (70,'Vingt-Quatre',24,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (71,'Twenty-Four',24,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (72,'Vierundzwanzig',24,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (73,'Vingt-Cinq',25,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (74,'Twenty-Five',25,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (75,'Fünfundzwanzig',25,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (76,'Vingt-Six',26,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (77,'Twenty-Sixe',26,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (78,'Sechsundzwanzig',26,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (79,'Vingt-Sept',27,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (80,'Twenty-Seven',27,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (81,'Siebenundzwanzig',27,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (82,'Vingt-Huit',28,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (83,'Twenty-Eight',28,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (84,'Achtundzwanzig',28,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (85,'Vingt-Neuf',29,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (86,'Twenty-Nine',29,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (87,'Neunundzwanzig',29,'DR');

INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (88,'Trente',30,'FR');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (89,'Thirty',30,'EN');
INSERT INTO LANGUAGE_TRANSLATE (ID,MESSAGE,NBR,LANGUE) VALUES (90,'Dreißig',30,'DR');







