CREATE TABLE IF NOT EXISTS LanguageTranslate(
id INTEGER PRIMARY KEY,
message VARCHAR(100)  NOT NULL,
nbr INTEGER(100) NOT NULL,
langue VARCHAR(100)  NOT NULL
);

INSERT INTO LanguageTranslate (ID,MESSAGE,NBR,LANGUE) VALUES (1,'UN',1,'FR');
INSERT INTO LanguageTranslate (ID,MESSAGE,NBR,LANGUE) VALUES (2,'ON',1,'EN');
INSERT INTO LanguageTranslate (ID,MESSAGE,NBR,LANGUE) VALUES (3,'EINS',1,'DR');
