CREATE TABLE IF NOT EXISTS french_translate(
number INTEGER PRIMARY KEY,
message VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS english_translate(
number INTEGER PRIMARY KEY,
message VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (1,'UN');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (1,'ON');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (2,'DEUX');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (2,'TWO');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (3,'TROIS');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (3,'TREE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (4,'QUATRE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (4,'FOUR');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (5,'CINQ');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (5,'FIVE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (6,'SIX');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (6,'SIX');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (7,'SEPT');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (7,'SEVEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (8,'HUIT');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (8,'EIGHT');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (9,'NEUF');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (9,'NINE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (10,'DIX');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (10,'TEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (11,'ONZE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (11,'ELEVEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (12,'DOUZE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (12,'TWELVE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (13,'TREIZE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (13,'THIRTEEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (14,'QUATORZE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (14,'FOURTEEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (15,'QUINZE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (15,'FIFTEEN');


INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (16,'SEIZE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (16,'SIXTEEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (17,'DIX-SEPT');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (17,'SEVENTEEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (18,'DIX-HUIT');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (18,'EIGHTEEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (19,'DIX-NEUF');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (19,'NINETEEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (20,'VINGT');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (20,'TWENTY');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (21,'VINGT-ET-UN');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (21,'TWENTY-ONE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (22,'VINGT-DEUX');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (22,'TWENTY-TWO');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (23,'VINGT-TROIS');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (23,'TWENTY-THREE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (24,'VINGT-QUATRE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (24,'TWENTY-FOUR');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (25,'VINGT-CINQ');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (25,'TWENTY-FIVE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (26,'VINGT-SIX');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (26,'TWENTY-SIX');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (27,'VINGT-SEPT');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (27,'TWENTY-SEVEN');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (28,'VINGT-HUIT');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (28,'TWENTY-EIGHT');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (29,'VINGT-NEUF');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (29,'TWENTY-NINE');

INSERT INTO french_translate (NUMBER,MESSAGE) VALUES (30,'TRENTE');
INSERT INTO english_translate (NUMBER,MESSAGE) VALUES (30,'THIRTY');


